name: Colab sync

on:
  workflow_dispatch:  # Permite iniciar o workflow manualmente
  schedule:
    - cron: '0 8 * * *'  # Executa diariamente às 8:00 UTC

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install nbconvert papermill pandas numpy  # Outras dependências necessárias

      - name: Execute Notebook with Papermill
        run: |
          papermill JOTFORM\ VU\ -\ TAMANDUATI.ipynb JOTFORM\ VU\ -\ TAMANDUATI_output.ipynb
