name: Atualizar e Rodar Código

on:
  schedule:
    - cron: '*/15 * * * *'  # Executa a cada 15 minutos


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Check current directory
        run: pwd

      - name: List files in root directory
        run: ls -la

      - name: List files in notebooks directory
        run: ls -la path/to/your/notebooks/

      - name: Execute notebook with papermill
        run: |
          papermill path/to/your/notebooks/JOTFORM_VU_TAMANDUATI.ipynb path/to/your/notebooks/JOTFORM_VU_TAMANDUATI_output.ipynb
